steps:
- name: 'eu.gcr.io/cloud-builders/git'
  args: ['clone', '--recursive', 'https://github.com/lextira/lexgate-docs', 'lexgate-docs']

- name: 'eu.gcr.io/$PROJECT_ID/docs-builder'
  args: ['-s', './src',
         '-d',  '../public']
  dir: 'lexgate-docs'

- name: 'eu.gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './public/*', 'gs://docs.lexgate.ch']
  dir: 'lexgate-docs'
